### ISSUE TITLE
Post Request Error

### ISSUE THREAD

**Issue by msingh-de** [OWOX/BigQuery-integrations#4]
Hello,

I tried to send the post request to the URL from the Trigger Tab. However the response I get back is as follows: 

A server error occurred.  Please contact the administrator.

Do you have any idea, as to why this error might occur?

Thanks in advance. 

Best 

Manni

**Comment by s-krava** [comment]
Hi @msingh-de,

It might occur due to incorrect format/values of POST request parameters or issues during function deployment. 

Could you provide some details about your issue: 

- integration, which you are using (mysql, http, ...)?;
- screens of your function settings and logs, example of your POST request.

You could post them here or send it directly to analytics-dev@owox.com. 

We will be glad to assist you!
